name: gastrohub_app
description: Frontend para Gastro & Hub
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  cupertino_icons: ^1.0.0
  introduction_screen: ^3.1.17
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.8.0
  http: ^1.4.0
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/welcome.svg
    - assets/images/orders.svg
    - assets/images/inventory.svg
    - assets/images/payments.svg
    - assets/images/google_logo.svg
    - .env
    - .env.local
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf