name: gastrohub_app
description: Frontend para Gastro & Hub
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_riverpod: ^2.0.0
  cupertino_icons: ^1.0.0
  introduction_screen: ^3.1.17
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.8.0
  http: ^1.4.0
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.0.2
  smooth_page_indicator: ^1.0.0
  wave: ^0.2.2
  logger: ^2.5.0
  flex_color_scheme: ^8.2.0
  qr_flutter: ^4.0.0
  awesome_snackbar_content: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/welcome.svg
    - assets/images/orders.svg
    - assets/images/inventory.svg
    - assets/images/payments.svg
    - assets/images/google_logo.svg
    - assets/images/background_00.png
    - assets/images/background_01.png
    - assets/images/allergens/
    - .env
    - .env.local
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf